# Generated by Django 4.2.2 on 2023-12-31 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessitem',
            name='yelp_avg_sentiment',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
